name = "FastFilter"
uuid = "5470531f-076d-47a9-aacb-e15e1e7f44ac"
authors = ["JokingHero <kornel.labun@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
